name: project_drone
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^8.1.2
  google_maps_flutter: ^2.5.0
  geolocator: ^12.0.0
  flutter_map: ^5.0.0
  flutter_screenutil: ^5.0.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  flutter_typeahead: ^4.8.0
  firebase_core: ^2.27.2
  cloud_firestore: ^4.15.10
  firebase_auth: ^4.18.0
  firebase_database: ^10.5.4
  flutter_open_street_map: ^0.0.4
  liquid_progress_indicator: ^0.4.0
  sleek_circular_slider: ^2.0.1
  toggle_switch: ^2.1.0
  syncfusion_flutter_gauges: ^24.1.45
  flutter_joystick: ^0.0.4
  location: ^6.0.2
  xml: ^6.1.0
  flutter_asset_manager: ^0.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/Islamabad.txt
    - images/Jinnah_Hall.txt
    - images/rawalpindi.txt

